"""Render every surface from the index's files (spec §10): README.md, ports/<id>.md,
feed/v1/index.json, llms.txt and the submit skill's generated files.

generate() reads only files and makes no API calls, so it runs without secrets and gives the
same output for the same files. generated_at moves only when other output changed.
"""

from __future__ import annotations

import html
import inspect
import json
import pprint
import re
from pathlib import Path

import jinja2
import jsonschema

from . import checks, media, store, validate
from .lifecycle import DECAY, LISTED, PULLED, TAKEN_DOWN, WITHDRAWN

STATUS_LABEL = {
    "developer-verified": "Developer-verified",
    "working": "Working",
    "partially-working": "Partially working",
    "not-working": "Not working",
}
STATUS_RANK = {"developer-verified": 0, "working": 1, "partially-working": 2, "not-working": 3}
PLATFORM_LABEL = {
    "gamecube": "GameCube", "wii": "Wii", "n64": "Nintendo 64", "ps1": "PlayStation",
    "ps2": "PlayStation 2", "xbox": "Xbox", "dreamcast": "Dreamcast", "pc": "PC", "other": "Other",
}
INPUT_LABEL = {"game-controller": "game controller", "hand-tracking": "hand tracking",
               "keyboard-mouse": "keyboard and mouse"}
EXPERIENCE_LABEL = {"2d": "2D", "3d-immersive": "3D immersive", "3d-shared-space": "3D shared space",
                    "3d-tabletop": "3D tabletop", "6dof-immersive": "6DoF immersive", "6dof-progressive": "6DoF progressive"}
BRAND_START = "<!-- trevorbilt:brand:start -->"
BRAND_END = "<!-- trevorbilt:brand:end -->"
FEED_VERSION = "1.4.0"
GEN_NOTE = "Generated by tools/avpindex/generate.py. Do not edit by hand."
OPTIONAL = {"status_notes": None, "visionos_min": None, "input": [], "tags": [], "description": None,
            "credits": [], "upstream": [], "source_ref": None,
            "experiences": [], "install": ["build"]}


class BrandError(RuntimeError):
    pass


def md(value: object, limit: int = 300) -> str:
    """Escape contributor text for Markdown files (mentions in files never notify)."""
    text = "" if value is None else " ".join(str(value).split())
    if len(text) > limit:
        text = text[: limit - 1] + "…"
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return re.sub(r"([\\`*_{}\[\]()#+!|~])", r"\\\1", text)


def attr(value: object, limit: int = 300) -> str:
    """Escape text for an HTML attribute in a Markdown file."""
    text = "" if value is None else " ".join(str(value).split())
    if len(text) > limit:
        text = text[: limit - 1] + "…"
    return html.escape(text, quote=True)


def _env(root: Path) -> jinja2.Environment:
    env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(root / "templates")),
                             autoescape=False, keep_trailing_newline=True,
                             trim_blocks=True, lstrip_blocks=True, undefined=jinja2.StrictUndefined)
    env.filters["md"] = md
    env.filters["attr"] = attr
    return env


def _date(value: str | None) -> str:
    return value[:10] if value else ""


# --- view model ---------------------------------------------------------------------

def brand_lines(brand: dict) -> dict:
    site = brand["site"]
    site_label = re.sub(r"^https?://", "", site).rstrip("/")
    return {
        "curated_line": f"Curated by {brand['curator_name']} ([@{brand['curator_github']}]"
                        f"(https://github.com/{brand['curator_github']})) · [{site_label}]({site})",
        "footer": f"Curated by trevorbilt · [{site_label}]({site})",
        "site_label": site_label,
    }


def brand_block(root: Path, brand: dict) -> str:
    lines = [BRAND_START]
    logo = str(brand.get("logo") or "")
    if logo.startswith("https://") or (logo and (root / logo).is_file()):
        lines += [f'<img src="{logo}" alt="Trevorbilt" width="200">', ""]
    lines += [f"# {brand['display_name']}", "", brand_lines(brand)["curated_line"], BRAND_END]
    return "\n".join(lines)


def developer_plain(entry: dict) -> str:
    """The developer as plain text, for the Unavailable ports record (no links)."""
    dev = entry.get("developer") or {}
    return f"{md(dev['name'], 80)} (@{dev['github']})" if dev.get("name") else f"@{dev['github']}"


def developer_display(entry: dict) -> str:
    dev = entry.get("developer") or {}
    handle = f"[@{dev['github']}](https://github.com/{dev['github']})"
    return f"{md(dev['name'], 80)} ({handle})" if dev.get("name") else handle


def view(entry_id: str, entry: dict, state: store.State, base_url: str, raw_url: str) -> dict:
    record = state.lifecycle.get(entry_id) or {}
    health = state.health.get(entry_id) or store.default_health()
    owner, name = validate.parse_repo_url(entry["repo"])
    sha = health.get("scanned_commit") or ""
    verified = None
    rec = (state.verified.get("records") or {}).get(entry_id)
    if rec and rec.get("verified") and rec.get("repo_id") == record.get("repo_id"):
        verified = {"on": str(rec.get("verified_on")), "commit": rec.get("verified_commit"),
                    "updated_since": bool(sha and rec.get("verified_commit") != sha)}
    status = entry["status"]
    lic = health.get("license") or {"spdx": None, "kind": "none"}
    if lic.get("kind") == "open-source":
        license_label = lic.get("spdx") or "Open source"
    elif lic.get("kind") == "custom":
        license_label = f"Custom ({lic['spdx']})" if lic.get("spdx") else "Custom license"
    else:
        license_label = "No license stated"
    since = health.get("commits_since_scan")
    if health.get("scan_state") == "unknown" or since is None:
        since_text = "commits since unknown"
    else:
        since_text = f"{since} commit{'s' if since != 1 else ''} since"
    if health.get("scan_kind") == "curator-reviewed":
        scan_label = f"Reviewed by the curator {_date(health.get('scanned_at'))} · {since_text}"
    else:
        scan_label = f"Scanned {_date(health.get('scanned_at'))} · {since_text}"
    trust = (f"✔ Verified by trevorbilt on {verified['on']}" + (" (repo updated since)" if verified["updated_since"] else "")
             if verified else STATUS_LABEL[status])
    game = entry.get("game") or {}
    return {
        "id": entry_id,
        "entry": {**OPTIONAL, **entry},
        "name": entry["name"],
        "game_title": game.get("title", ""),
        "platform": game.get("original_platform"),
        "platform_label": PLATFORM_LABEL.get(game.get("original_platform") or "", ""),
        "year": game.get("original_release_year"),
        "repo": entry["repo"],
        "repo_owner": owner,
        "repo_name": name,
        "developer": developer_display(entry),
        "dev_github": (entry.get("developer") or {}).get("github"),
        "dev_name": (entry.get("developer") or {}).get("name"),
        "status": status,
        "status_label": STATUS_LABEL[status],
        "status_rank": STATUS_RANK[status],
        "verified": verified,
        "tier": "owner-verified" if verified else status,
        "trust": trust,
        "curator_own": bool(health.get("curator_own")),
        "health": health.get("health", "ok"),
        "health_label": "⚠ May have issues" if health.get("health") == "issues" else "OK",
        "failing_since": health.get("failing_since"),
        "license": lic,
        "license_label": license_label,
        "last_commit_date": health.get("last_commit_date"),
        "last_commit": _date(health.get("last_commit_date")),
        "archived": bool(health.get("archived")),
        "scanned_commit": sha,
        "scanned_at": health.get("scanned_at"),
        "scan_kind": health.get("scan_kind") or "automated",
        "commits_since": since,
        "scan_state": health.get("scan_state", "unknown"),
        "scan_label": scan_label,
        "github_verified": bool(health.get("github_verified")),
        "install_url": f"https://github.com/{owner}/{name}/blob/{sha}/AVP-INSTALL.md",
        "source_url": f"https://github.com/{owner}/{name}/tree/{sha}",
        "clone": f"git clone {entry['repo']} && cd {name} && git checkout {sha} && git submodule update --init --recursive",
        "page_url": f"{base_url}/ports/{entry_id}.md",
        "raw_page_url": f"{raw_url}/ports/{entry_id}.md",
        "inputs": ", ".join(INPUT_LABEL.get(i, i) for i in entry.get("input") or []),
        "experiences": ", ".join(EXPERIENCE_LABEL[k] for k in EXPERIENCE_LABEL if k in (entry.get("experiences") or [])),
        "sideload": "sideload" in (entry.get("install") or []),
        "listed_at": record.get("listed_at"),
        "changed_at": record.get("changed_at"),
        "media": None if entry.get("media") is False else media.feed_block(state.media.get(entry_id)),
    }


def sort_key(item: dict) -> tuple:
    last = item["last_commit_date"] or ""
    return (0 if item["verified"] else 1, item["status_rank"], _neg(last), item["id"])


def _neg(text: str) -> str:
    # sort ISO dates descending inside an ascending tuple sort
    return "".join(chr(0x10FFFF - ord(c)) for c in text)


def build_model(root: Path, repo_full: str) -> dict:
    policy = store.load_policy(root)
    brand = store.load_brand(root)
    state = store.State.load(root)
    entries, _errors = store.load_entries(root)
    base_url, raw_url = store.site_urls(policy, repo_full)
    listed, unavailable, tombstones = [], [], []
    for entry_id, record in sorted(state.lifecycle.items()):
        status = record.get("status")
        entry = entries.get(entry_id)
        if status == LISTED and entry and (state.health.get(entry_id) or {}).get("scanned_commit"):
            listed.append(view(entry_id, entry, state, base_url, raw_url))
        elif status == DECAY and entry:
            unavailable.append({
                "id": entry_id, "entry": entry, "name": entry.get("name", entry_id),
                "game_title": (entry.get("game") or {}).get("title", ""),
                "developer": developer_plain(entry),
                "credits": [{"name": c.get("name"), "role": c.get("role"), "url": c.get("url")}
                            for c in entry.get("credits") or []],
                "listed_at": record.get("listed_at"), "unavailable_since": record.get("changed_at"),
                "last_scanned_commit": (state.health.get(entry_id) or {}).get("scanned_commit"),
            })
        elif status in (PULLED, TAKEN_DOWN, WITHDRAWN):
            tombstones.append({"id": entry_id, "removed_at": record.get("changed_at")})
    listed.sort(key=sort_key)
    return {"policy": policy, "brand": brand, "brand_block": brand_block(root, brand),
            **brand_lines(brand), "base_url": base_url, "raw_url": raw_url, "repo_full": repo_full,
            "listed": listed, "unavailable": unavailable, "tombstones": tombstones}


# --- outputs ------------------------------------------------------------------------

def feed(model: dict, generated_at: str) -> dict:
    brand = model["brand"]

    def credit(c: dict) -> dict:
        return {"name": c.get("name"), "role": c.get("role"), "url": c.get("url")}

    entries = []
    for v in model["listed"]:
        e = v["entry"]
        game = e.get("game") or {}
        dev = e.get("developer") or {}
        entries.append({
            "id": v["id"], "name": e["name"],
            "game": {"title": game.get("title"), "original_platform": game.get("original_platform"),
                     "original_release_year": game.get("original_release_year")},
            "repo_url": e["repo"], "source_ref": e.get("source_ref"), "source_url": v["source_url"],
            "install_doc_url": v["install_url"],
            "developer": {"name": dev.get("name"), "github": dev["github"], "url": dev.get("url"),
                          "github_verified": v["github_verified"]},
            "credits": [credit(c) for c in e.get("credits") or []],
            "upstream": list(e.get("upstream") or []),
            "self_reported_status": e["status"], "status_notes": e.get("status_notes"),
            "owner_verified": {"verified": bool(v["verified"]),
                               "verified_on": v["verified"]["on"] if v["verified"] else None,
                               "verified_commit": v["verified"]["commit"] if v["verified"] else None},
            "trust_tier": v["tier"], "curator_own": v["curator_own"],
            "health": {"status": v["health"], "failing_since": v["failing_since"]},
            "scanned_commit": v["scanned_commit"], "scanned_at": v["scanned_at"],
            "scan_kind": v["scan_kind"], "commits_since_scan": v["commits_since"],
            "scan_state": v["scan_state"], "archived": v["archived"],
            "last_commit_date": v["last_commit_date"], "license": v["license"],
            "visionos_min": e.get("visionos_min"), "input": list(e.get("input") or []),
            "experiences": [k for k in EXPERIENCE_LABEL if k in (e.get("experiences") or [])],
            "install": [k for k in ("build", "sideload") if k in (e.get("install") or ["build"])],
            "tags": list(e.get("tags") or []), "description": e.get("description"),
            "page_url": v["page_url"], "media": v["media"],
        })
    unavailable = [{
        "id": u["id"], "name": u["name"], "game": {"title": u["game_title"]},
        "developer": {"name": (u["entry"].get("developer") or {}).get("name"),
                      "github": (u["entry"].get("developer") or {}).get("github", "")},
        "credits": [credit(c) for c in u["credits"]],
        "listed_at": u["listed_at"], "unavailable_since": u["unavailable_since"],
        "last_scanned_commit": u["last_scanned_commit"],
    } for u in model["unavailable"]]
    return {
        "$schema": f"{model['raw_url']}/schema/feed-v1.schema.json",
        "schema_version": FEED_VERSION,
        "identifier": "com.trevorbilt.avp-ports-index",
        "generated_at": generated_at,
        "publisher": {"name": "trevorbilt", "curator": brand["curator_name"],
                      "github": brand["curator_github"], "url": brand["site"], "contact": brand["contact"]},
        "license": "CC0-1.0",
        "entries": entries,
        "unavailable": unavailable,
        "tombstones": model["tombstones"],
    }


def entry_fields_md(schema: dict) -> str:
    lines = [f"<!-- {GEN_NOTE} -->", "", "# Entry fields", "",
             "Every field allowed in `entries/<id>.yaml`. Anything else fails the schema check (S1-03).", "",
             "| Field | Required | Allowed values | Notes |", "| --- | --- | --- | --- |"]

    def constraint(prop: dict) -> str:
        if "$ref" in prop:
            return "https URL"
        if "enum" in prop:
            return ", ".join(f"`{v}`" for v in prop["enum"])
        if "const" in prop:
            return f"`{prop['const']}`"
        kind = prop.get("type", "")
        parts = []
        if kind == "string":
            if "pattern" in prop:
                parts.append(f"pattern `{prop['pattern']}`")
            if "minLength" in prop or "maxLength" in prop:
                parts.append(f"{prop.get('minLength', 0)} to {prop.get('maxLength', '∞')} characters")
        elif kind == "integer":
            parts.append(f"integer {prop.get('minimum')} to {prop.get('maximum')}")
        elif kind == "array":
            items = prop.get("items", {})
            inner = constraint(items) if items else ""
            parts.append(f"list{' of ' + inner if inner else ''}" + (f", at least {prop['minItems']}" if "minItems" in prop else "")
                         + (f", at most {prop['maxItems']}" if "maxItems" in prop else "")
                         + (f", must include `{prop['contains']['const']}`" if "const" in prop.get("contains", {}) else ""))
        elif kind == "object":
            parts.append("object")
        return "; ".join(parts) or kind

    def walk(props: dict, required: list, prefix: str) -> None:
        for key, prop in props.items():
            path = f"{prefix}{key}"
            desc = (prop.get("description") or "").replace("|", "\\|")
            lines.append(f"| `{path}` | {'yes' if key in required else 'no'} | {constraint(prop)} | {desc} |")
            if prop.get("type") == "object" and "properties" in prop:
                walk(prop["properties"], prop.get("required", []), f"{path}.")
            if prop.get("type") == "array" and isinstance(prop.get("items"), dict) and "properties" in prop["items"]:
                walk(prop["items"]["properties"], prop["items"].get("required", []), f"{path}[].")

    walk(schema["properties"], schema.get("required", []), "")
    lines += ["", "Missing optional fields are left out of the README and port pages, and are `null` (or empty lists) in the feed.", ""]
    return "\n".join(lines)


def checks_md() -> str:
    lines = [f"<!-- {GEN_NOTE} -->", "", "# Stage 1 checks", "",
             "These run on every entry PR, right away and for free. `scripts/preflight.py` runs the ones that "
             "don't need the index's own data. A **fail** is something to fix; a **route** means the curator "
             "looks before the PR goes further.", "",
             "| Check | What it checks | PR gate | Daily health check | Preflight |",
             "| --- | --- | --- | --- | --- |"]
    for func in checks.ALL_CHECKS:
        doc = " ".join(inspect.getdoc(func).split())
        check_id, _, rest = doc.partition(" · ")
        title, _, body = rest.partition(". ")
        gate = "yes"
        health = "yes" if check_id in checks.HEALTH_IDS else ""
        pre = "" if check_id in checks.PREFLIGHT_SKIPS else "yes"
        lines.append(f"| {check_id} {title} | {body.replace('|', '/')} | {gate} | {health} | {pre} |")
    lines.append("")
    return "\n".join(lines)


def preflight_source(root: Path) -> str:
    """A standalone copy of the Stage 1 checker for the submit skill."""
    pkg = root / "tools" / "avpindex"
    policy = store.load_policy(root)
    keep = {k: policy[k] for k in ("license_open_source", "license_route_phrases", "install_file",
                                   "forbidden_extensions", "archive_extensions", "large_blob_bytes",
                                   "release_binary_extensions")}
    schema = store.load_json("schema/entry.schema.json", root)

    def body(name: str) -> str:
        text = (pkg / name).read_text(encoding="utf-8")
        text = text.replace("from __future__ import annotations\n", "")
        return re.sub(r"^from \.[\w.]* import [^\n]*\n", "", text, flags=re.M)

    main = (pkg / "preflight_main.py").read_text(encoding="utf-8")
    main = main.replace("from __future__ import annotations\n", "")
    main = re.sub(r"^from \.[\w.]* import [^\n]*\n", "", main, flags=re.M)
    return "\n".join([
        "#!/usr/bin/env python3",
        f"# {GEN_NOTE}",
        "# Standalone copy of the AVP Ports Index Stage 1 checker (tools/avpindex/validate.py and checks.py).",
        "# Requires Python 3.11+ and: pip install pyyaml jsonschema requests",
        "from __future__ import annotations",
        "",
        f"POLICY = {pprint.pformat(keep, width=100, sort_dicts=False)}",
        f"SCHEMA = {pprint.pformat(schema, width=100, sort_dicts=False)}",
        "",
        "# ---- validate.py ----",
        body("validate.py"),
        "# ---- checks.py ----",
        body("checks.py"),
        "# ---- preflight ----",
        main,
    ])


def assert_brand(outputs: dict[str, str], model: dict) -> None:
    brand = model["brand"]
    readme = outputs["README.md"]
    for needle in (BRAND_START, BRAND_END, f"# {brand['display_name']}", model["curated_line"], model["footer"]):
        if needle not in readme:
            raise BrandError(f"README.md is missing its brand element: {needle[:40]}")
    for path, text in outputs.items():
        if path.startswith("ports/") and model["footer"] not in text:
            raise BrandError(f"{path} is missing the brand footer")
    llms = outputs["llms.txt"]
    if not llms.startswith("# AVP Ports Index\n") or brand["curator_name"] not in llms.split("\n\n")[1]:
        raise BrandError("llms.txt is missing its brand heading or curator")
    data = json.loads(outputs["feed/v1/index.json"])
    if data.get("publisher", {}).get("curator") != brand["curator_name"]:
        raise BrandError("feed is missing its publisher")


def render_all(root: Path, model: dict, generated_at: str) -> dict[str, str]:
    env = _env(root)
    out: dict[str, str] = {}
    ctx = dict(model, generated_at=generated_at)
    out["README.md"] = env.get_template("README.md.j2").render(**ctx)
    for v in model["listed"]:
        out[f"ports/{v['id']}.md"] = env.get_template("port.md.j2").render(v=v, **ctx)
    out["llms.txt"] = env.get_template("llms.txt.j2").render(**ctx)
    data = feed(model, generated_at)
    jsonschema.Draft202012Validator(store.load_json("schema/feed-v1.schema.json", root)).validate(data)
    out["feed/v1/index.json"] = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    schema = store.load_json("schema/entry.schema.json", root)
    out["skills/avp-index-submit/references/entry-fields.md"] = entry_fields_md(schema)
    out["skills/avp-index-submit/references/checks.md"] = checks_md()
    out["skills/avp-index-submit/scripts/preflight.py"] = preflight_source(root)
    return out


def previous_generated_at(root: Path) -> str | None:
    path = root / "feed/v1/index.json"
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8")).get("generated_at")
        except ValueError:
            return None
    return None


def generate(root: Path | None = None, repo_full: str = "edgytoast/avp-ports-index",
             *, write: bool = True) -> dict[str, str]:
    """Render and (by default) write every surface. Returns {path: text}."""
    root = root or store.ROOT
    model = build_model(root, repo_full)
    previous = previous_generated_at(root)
    outputs = render_all(root, model, previous or store.iso(store.utcnow()))
    if previous and _differs(root, outputs):
        outputs = render_all(root, model, store.iso(store.utcnow()))
    assert_brand(outputs, model)
    if write:
        for path, text in outputs.items():
            store.write_text_if_changed(root / path, text)
        keep = {p for p in outputs if p.startswith("ports/")}
        for page in (root / "ports").glob("*.md"):
            if f"ports/{page.name}" not in keep:
                page.unlink()
        (root / "skills/avp-index-submit/scripts/preflight.py").chmod(0o755)
    return outputs


def _differs(root: Path, outputs: dict[str, str]) -> bool:
    for path, text in outputs.items():
        file = root / path
        if not file.exists() or file.read_text(encoding="utf-8") != text:
            return True
    expected = {p for p in outputs if p.startswith("ports/")}
    existing = {f"ports/{p.name}" for p in (root / "ports").glob("*.md")}
    return expected != existing
